Revert token handling logic in _GISResource
1) current logic leads to geocoding error:
AttributeError: 'Geocoder' object has no attribute '_lazy_properties'

2) prevents leakage of GIS token as it always attempts to get server
token instead of using GIS token - using _con.token does not attempt to
fetch server token in all cases leading to leakage of GIS token

cc: @achapkowski