added cache manager to image services (elevation layer) (#2131)
* - reverted back all user id to usernames to fix issues with portal 10.7 not honoring the ID.

* fixed syntax

* - Added notebook server code.

* - Various NotebookManager fixes.
- Minor tweak to connection.py to support Empty Form Post Variables for files. (Notebook Server Requirement)

* - Doc string fixes
- Switched POST to GET for /config
- added missing comma on _add_runtime

* Add pytest for notebook admin api

* - Fixed missing '/' in DirectoryManager unregister method.

* - fixed GIS reference issue.

* - Fixed issue where JSON was not correct for OfflineMapAreaManager.create and OfflineMapAreaManager.modify_refresh_schedule. BUG-000119314 The refresh_schedule parameter of the create method in arcgis.mapping.offlineMapAreaManager is not reflected in the ArcGIS Online user interface. #1675

* - Fixes issue: BUG-000119931 from_shapely method fails with NameError: name 'self' is not defined in ArcGIS Pro #1713 and https://github.com/Esri/arcgis-python-api/issues/331 New from_shapely() method - NameError: name 'self' is not defined #331

* - Added Support for PyShp 2.0

* Fixed geometry issue with WKB values.

* - fixed Geocoders and GIS.map() #1712
- fixed issue when a geocoder is a composite geocoder and does not return valid results, the result is ignored.

* - Resolved doc update and code enforcement of versioning.  BUG-000119981 gis.content.import() does not import the correct attribute type with Pandas datetime if the column name and variable name are different. #1717

* - Added missing invite parameters.

* - Added credit estimation logic. related to: #1724
- made adding a gptool optional (the default is use the gptool._token like before) but some webtools fail when token generated this way.

* - code clean up

* - Added credit estimator function on _FeatureAnalysisTools.  #1724

* - Added deprecation warning to SpatialDataFrame property on FeatureSet
- ImageryLayer's `get_samples` switched from GET to POST to support long queries.

* - Added glr and forest to the analyze_patterns.py
- Added glr and forest to help documentation.

* - More GA fixes, doc string, tool changes.

* - updated doc, fixed issue with TrainAndPredict not working if features_to_predict isn't specified.

* - Docstring fixes and rst updates.

* - fixed in logging.warning(f'feature {i} contains more than 50 categories, dropping!!')

* - Added SDF warnings back in.

* - updated name for describe_dataset, modified some variable names.

* - fix for #1773, #1774, #1775

* Added two new methods off of SeDF.spatial to create distance matrix (distance_matrix) and voronoi diagrams from a given SeDF.

* - updated help on Geometry objects to resolve issue: arcgis.geometry._types.Geometry#project_as(...) needs to add arcpy pre-requisite #1788

* resoles issue: BUG-000120125 Fail to access license attribute of class arcgis.gis.admin.System in ArcGIS API for Python when connecting to Portal for ArcGIS 10.7 Pre #1763

* - Added overlay tool on SeDF
- Added Select By Location tool on SeDF

* - Added note in doc string that arcpy or shapely is needed.

* - Updated the Help/DocString in arcgis.gis.admin.rst
- Renamed License to PortalLicense to avoid naming conflict with AGOL License class.
- Updated Licenses docstring to state that this Class is Deprecated at Enterprise 10.7

* - Added Spatial Operations
- added relationship method

* - rst fixed as per comment.

* - Added license_types for UserManager to assist with creating users.

* - Added CategorySchemaManager to allow general user to update the Item and Group categories.  Resolves: https://github.com/ArcGIS/geosaurus/issues/1800

* - Updated rst file for help doc.

* - resolves: https://github.com/ArcGIS/geosaurus/issues/1761 -Updated the help doc to be IDs not titles.

* - resolved: https://github.com/ArcGIS/geosaurus/issues/1760 - had to add spatialReference, Name and id to the `fc_layer_definition`

* - resolved: ENH-000118666 Provide functionality within the ArcGIS API for Python to rename ArcGIS Online content folders. #1784

* Fixed variable

* - resolved: BUG-000119821 'usage_reports' from AGOLAdminManager start date does not correspond with the input parameter. #1759

* - fixed: Survey123 generate_report function - where parameter is wrong #1816

* - resolved: https://github.com/ArcGIS/geosaurus/issues/1828

* - Added spatial reference check to is_valid on Geometry objects

* - resolved: Issue: 1869 - 'License.plot()' method returning 'KeyError' - Introduced at: 10.7. This bug is being caused by license changes in the REST API on Portal.

* - resolved: sedf.spatial.plot() does not plot when columns have spaces #1873

* - Added loc='best' to plot() method on license.plot()

* - Cleaned up commented out code
- Removed unneeded logic from from_layer and just leverage paging on FeatureLayer.query()
- Resolved: sdf.spatial.to_featureclass doesn't work and DATETIME field is NaT with a particular feature layer #1876.  Fix was pd.NaT is not honored as NULL with pyshp.

* - allow int and str to auto convert to SpatialReference
- With ArcPy, the `spatial_reference` property on Geometry should return SpatialReference not arcpy.SpatialReference when ArcPy is present.

* - Removed extra '/' in URL path.

* - fix issue in Notebook Server Admin where the url was incorrect for sessions.

* - resolves: GeoAnalytics: allow writing to BDFS templates #1418

* - updated help docs/api_ref/source/arcgis.geoanalytics.toc.rst
- updated help on define_output_datastore
- added two string value to accept to define_output_datastore.

* - Added case for invalid strings on GA helper
- Fixed issue where SR is not coming back as arcpy.SpatialReference.

* - Updated `template` wording for GA helper.

* - resolved: GeoAnalytics: Add spatial relationship to join_features for Near Geodesic #1787. Updated the help.

* - Fixed issue where `choose_best_facilities` not showing in find_locations.py

* - updated create user logic to accept level 1/2 instead of specifying user types/roles for newer user types.

* - Fixed issue where verify_cert = False does not always ignore errors with certificates.

* revert changes from connection object.

* - Added some missing properties on the FeatureCollection JSON
- Made PKI support ignore certificate when requested.

* - Fix for to_feature_collection method to ensure unique OBJECTID.

* - fixed typo in renderer.py
- added missing __str__ and __repr__ to LicenseManager

* - Added missing parameters to query_related_records.

* - updated some doc

* - Fixed estimate on `create_route_layers`

* - added missing parameter.

* - removed update to query_related_records

* - Add Dot Density Support to SeDF `plot()` #1882

* - added output save folder for item.get_data()

* - Added support for 7.2 API of AGOL for the `OfflineMapAreaManager.create`.  Handles internal parameter position and name changes.

* - resolved: Unsupported types for GeoJSON in get_geometry(...) #1978

* - Added magic function for spatially enabled dataframe to make the import process easier in Jupyter Notebooks.

* - remove magic logic on arcgis import.

* - removed commented out code (code clean up)

* - Added _repr_svg_ to sdf.spatial.
- Fixed `svg` on Polygon where multi-part polygons were not rendering correctly.

* - reverted get_data()'s folder option as per comment.

* - Added MultiPoint GeoJSON support.

* - resolved Add "pointBarrierLayer", "lineBarrierLayer", "polygonBarrierLayer" to plan routes tool. #1600

* - removed unneeded code.

* - removed unneeded magic code.

* - added handle to ensure SeDF.plot() has punctuation values removed from field names when mapping.

* - resolved: ImportError: cannot import name 'parse_version' #1998

* - added parameters to return messages as a dictionary from _execute_gp_tool.  This is needed for geoanalytics
- Added run_python_script method to allow for direct scripting on spark.
- updated the help to include the run_python_script method.

* - Updated documentation per request.

* - Added 10.7.1 Administration Operation to NotebookServer (export/import site)
- Added missing methods on FeatureLayerCollection: relationships (10.7) and query_domains (10.5)
- Added property to access the site operations on NotebookServer class.

* - Added new parameters for 10.7 EnterpriseUsers.create and updated help documentation
- Added new parameters for 10.7/10.7.1 for _site.py's create method.
- Updated help doc for System.properties

* - Fixed syntax error in query_domains

* - Added PortalDataStore which manages datastores through the 10.7.1+ new REST API.

* - Updated docstrings as requested.
- Added Datastore controls for 10.7.1
- Add support for bulk publishing in ArcGIS Enterprise 10.7.1 #1868

* - added size property to GeoArray. Allows for the pd.Series.size call to work.

* - Fixed unicode errors.

* - Fixed input error on PlatformService

* - Added geoprocessing admin jobs manager.

* - Added missing REST API to get the Item Information. This includes the item information and manifest.json file.

* - Fixed Indentation
-  _find_and_replace_mosaic_rule had variable reference that do not exist change fnarg to fnarg_ra

* - fix for property is_valid on GeoArray.

* - Fix for: Raster Fails to Load in ImageLayer #1753

* - Added Functionality - GeoAnalytics: Add the capability to re-generate a manifest #1416

* - fixed typo in regenerate.

* - Fixed for Creating users from csv fails in ArcGIS Online #1404

* - Fixed: BUG-000119377 Delete_certificate(certificate) function in arcgis.server module returns "Error" #1676

* - Fixed: BUG-000118809 The job_statistics method fails when using the jobID of updating tiles in ArcGIS API for Python. #1596

* - Added curvedRing support for is_valid

* - Enforce same index in = index out

* - Docstring fix on to_geo

* - added missing `calculate` parameters

* - fix f-string syntax.

* - added: Support QueryTopFeatures Endpoint #2056

* - resolves: Print out message that you are an org_admin on GIS("home") connections #2055

* - fixed issue where 'Hub Site Application' could not be registered by the Python API

* -fixed docstring issues.

* - resolves issue: Add support for importTiles operation on tiled map service layers #2061

* - Added missing export type in docstring for Item.export

* - additional missing part of the new export type excel on Item.export()

* - Added test for can_delete
- Added `can_delete` method to contentmanager.

* - Fix for AdminServiceFactory modifies case of url on Linux stand-alone services #2096

* - Fixed spelling mistake in doc string.

* - Fixed issue with buffer units parameter.

* - added multi-upload support when adding large files. Performs 5 uploads at once if needed for large uploads.

* - improved the get property performance on SeDF for the `sr` property
- corrected the doc string error. SEDF: project documentation incorrect and maybe project is broken #2113

* - Added ability to manage cache based image services on AGOL hosted image layers.

* - handled Image Layer Elevation data case with build cache = True, and False on `publish`.

* - updated class names

* - lowered multipart size from 15mb to 7mb to improve upload speed.

* - Fixed Documentation: BUG-000120345 Update documentation to inform users that the 'calculate_volume' method is only supported at 10.7+ for the esriImageServiceDataTypeElevation service type. #1782

* - fixed issue with numpy.Int64 causes json.dumps to fail.

* - fixed export issue: BUG-000120311 The export method of the arcgis.gis module in the ArcGIS API for Python does not respect the Set View Definition of hosted feature layer views when the view definition is Define Fields. #1765

* - Fix: ArcGIS Online create_tile_service Runtime Error #1707

* - resolved: Return hardware information for all servers #2147

* - docstring fix.

* - Fixed: Parameter issue in doc - Not sure which one is correct #2145

* - Fix: GeoAnalytics find_point_cluster tool fails #2149

* - modified based on the review.